# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atba.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Atbash(object):
    def setupUi(self, Atbash):
        Atbash.setObjectName("Atbash")
        Atbash.setFixedSize(800, 624)
        icon = QIcon("icons/icon.png")
        Atbash.setWindowIcon(icon)
        Atbash.setStyleSheet("background-color: rgb(222, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(Atbash)
        self.centralwidget.setObjectName("centralwidget")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 0, 281, 41))

        font2 = QtGui.QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(75)

        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 801, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.textEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.encrypt)
        self.verticalLayout.addWidget(self.pushButton_3)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_11.setFont(font)
        self.label_11.setToolTipDuration(-1)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.textBrowser_2)
        Atbash.setCentralWidget(self.centralwidget)

        self.retranslateUi(Atbash)
        QtCore.QMetaObject.connectSlotsByName(Atbash)

        self.copyright = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(180, 590, 431, 31))
        self.copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copyright.setObjectName("copyright")
        self.copyright.setText("© Виноградов К.С., Шифратор, 2023")
        self.copyright.setFont(font2)

    def retranslateUi(self, Atbash):
        _translate = QtCore.QCoreApplication.translate
        Atbash.setWindowTitle(_translate("Atbash", "Atbash"))
        self.label_9.setText(_translate("Atbash", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Шифр Атбаш</span></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label_10.setText(_translate("Atbash", "Введите шифруемый текст:"))
        self.pushButton_3.setText(_translate("Atbash", "Зашифровать"))
        self.label_11.setText(_translate("Atbash", "Зашифрованный текст:"))

    def encrypt(self):
        plaintext = self.textEdit_3.toPlainText()
        encrypted_text = self.atbash_encrypt(plaintext)
        self.textBrowser_2.setPlainText(encrypted_text)

    def atbash_encrypt(self, text):
        encrypted_text = ""
        for char in text:
            if char.isalpha():
                shift = ord('а') if char.islower() else ord('А')
                encrypted_char = chr(shift + 31 - (ord(char) - shift))
            else:
                encrypted_char = char
            encrypted_text += encrypted_char

        return encrypted_text


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Atbash = QtWidgets.QMainWindow()
    ui = Ui_Atbash()
    ui.setupUi(Atbash)
    Atbash.show()
    sys.exit(app.exec_())