# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caes.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Caesar(object):
    def setupUi(self, Caesar):
        Caesar.setObjectName("Caesar")
        Caesar.setFixedSize(800, 600)
        icon = QIcon("icons/icon.png")
        Caesar.setWindowIcon(icon)
        Caesar.setStyleSheet("background-color: rgb(222, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(Caesar)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 0, 281, 41))

        font2 = QtGui.QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(75)

        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 30, 801, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.encrypt_text)

        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(30, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)


        self.label_slide = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_slide.setObjectName("lcdNumber")
        self.label_slide.setFont(font)
        self.horizontalLayout.addWidget(self.label_slide)

        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)

        self.horizontalSlider.setOrientation(1)  # Горизонтальное расположение
        self.horizontalSlider.setMinimum(1)  # Минимальное значение шага
        self.horizontalSlider.setMaximum(32)  # Максимальное значение шага (для русского алфавита)
        self.horizontalSlider.setValue(3)  # Значение по умолчанию
        self.horizontalSlider.setTickPosition(1)  # Отображать значения шага
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setRange(1, 32)

        self.horizontalSlider.valueChanged.connect(self.updateLabel)

        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setToolTipDuration(-1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFontPointSize(16)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.textBrowser)
        Caesar.setCentralWidget(self.centralwidget)

        self.copyright = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(180, 570, 431, 31))
        self.copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copyright.setObjectName("copyright")
        self.copyright.setText("© Виноградов К.С., Шифратор, 2023")
        self.copyright.setFont(font2)




        self.retranslateUi(Caesar)
        QtCore.QMetaObject.connectSlotsByName(Caesar)

    def retranslateUi(self, Caesar):
        _translate = QtCore.QCoreApplication.translate
        Caesar.setWindowTitle(_translate("Caesar", "Caesar"))
        self.label_2.setText(_translate("Caesar", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Шифр Цезаря</span></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("Caesar", "Введите шифруемый текст:"))
        self.pushButton.setText(_translate("Caesar", "Зашифровать"))
        self.label_4.setText(_translate("Caesar", "Ключ:"))
        self.label_3.setText(_translate("Caesar", "Зашифрованный текст:"))




    def updateLabel(self, value):

        self.label_slide.setText(str(value))


    def encrypt_text(self):
        text = self.textEdit.toPlainText()
        shift = self.horizontalSlider.value()

        encrypted_text = self.caesar_cipher(text, shift)

        self.textBrowser.setPlainText(encrypted_text)

    def caesar_cipher(self, text, shift):
        encrypted_text = ''
        for char in text:
            if char.isalpha():
                shift_amount = shift % 32  # Чтобы не выйти за пределы букв русского алфавита
                if char.islower():
                    encrypted_char = chr(((ord(char) - ord('а') + shift_amount) % 32) + ord('а'))
                else:
                    encrypted_char = chr(((ord(char) - ord('А') + shift_amount) % 32) + ord('А'))
                encrypted_text += encrypted_char
            else:
                encrypted_text += char
        return encrypted_text




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Caesar = QtWidgets.QMainWindow()
    ui = Ui_Caesar()
    ui.setupUi(Caesar)
    Caesar.show()
    sys.exit(app.exec_())