# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mors.ui'
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mors.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
import winsound
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

# Словарь для азбуки Морзе с русским алфавитом
morse_code = {
    'А': '.-', 'Б': '-...', 'В': '.--', 'Г': '--.', 'Д': '-..', 'Е': '.',
    'Ж': '...-', 'З': '--..', 'И': '..', 'Й': '.---', 'К': '-.-', 'Л': '.-..',
    'М': '--', 'Н': '-.', 'О': '---', 'П': '.--.', 'Р': '.-.', 'С': '...',
    'Т': '-', 'У': '..-', 'Ф': '..-.', 'Х': '....', 'Ц': '-.-.', 'Ч': '---.',
    'Ш': '----', 'Щ': '--.-', 'Ъ': '--.--', 'Ы': '-.--', 'Ь': '-..-', 'Э': '..-..',
    'Ю': '..--', 'Я': '.-.-',
    '0': '-----', '1': '.----', '2': '..---', '3': '...--', '4': '....-',
    '5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.',
    '.': '.-.-.-', ',': '--..--', '?': '..--..', "'": '.----.', '!': '-.-.--',
    '/': '-..-.', '(': '-.--.', ')': '-.--.-', '&': '.-...', ':': '---...',
    ';': '-.-.-.', '=': '-...-', '+': '.-.-.', '-': '-....-', '_': '..--.-',
    '"': '.-..-.', '$': '...-..-', '@': '.--.-.'
}


class Ui_Morse(object):
    def setupUi(self, Morse):
        Morse.setObjectName("Morse")
        Morse.setFixedSize(800, 600)
        icon = QIcon("icons/icon.png")
        Morse.setWindowIcon(icon)
        Morse.setStyleSheet("background-color: rgb(222, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(Morse)
        self.centralwidget.setObjectName("centralwidget")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(230, 0, 281, 41))

        font2 = QtGui.QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(75)

        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 29, 801, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.encrypt)
        self.verticalLayout.addWidget(self.pushButton_4)
        self.textEdit_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout.addWidget(self.textEdit_4)

        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setToolTipDuration(-1)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_3.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.verticalLayout.addWidget(self.textBrowser_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.play_morse)
        self.verticalLayout.addWidget(self.pushButton_5)
        Morse.setCentralWidget(self.centralwidget)

        self.retranslateUi(Morse)
        QtCore.QMetaObject.connectSlotsByName(Morse)

        self.copyright = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(180, 570, 431, 31))
        self.copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copyright.setObjectName("copyright")
        self.copyright.setText("© Виноградов К.С., Шифратор, 2023")
        self.copyright.setFont(font2)

    def retranslateUi(self, Morse):
        _translate = QtCore.QCoreApplication.translate
        Morse.setWindowTitle(_translate("Morse", "Morse"))
        self.label_12.setText(_translate("Morse", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Азбука Морзе</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label_13.setText(_translate("Morse", "Введите шифруемый текст:"))
        self.pushButton_4.setText(_translate("Morse", "Зашифровать"))

        self.label_14.setText(_translate("Morse", "Зашифрованный текст:"))
        self.pushButton_5.setText(_translate("Morse", "Прослушать"))

    def encrypt(self):
        plaintext = self.textEdit_4.toPlainText().upper()
        morse_text = self.text_to_morse(plaintext)
        self.textBrowser_3.setPlainText(morse_text)

    def text_to_morse(self, text):
        morse_text = ""
        for char in text:
            if char in morse_code:
                morse_text += morse_code[char] + ' '
            elif char == ' ':
                morse_text += ' '
        return morse_text.strip()

    def play_morse(self):
        morse_text = self.textBrowser_3.toPlainText()
        for char in morse_text:
            if char == '.':
                winsound.Beep(1000, 200)  # Воспроизвести точку
            elif char == '-':
                winsound.Beep(1000, 600)  # Воспроизвести тире
            elif char == ' ':
                time.sleep(0.3)  # Пауза между символами
            else:
                time.sleep(0.7)  # Пауза между словами


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Morse = QtWidgets.QMainWindow()
    ui = Ui_Morse()
    ui.setupUi(Morse)
    Morse.show()
    sys.exit(app.exec_())