# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'varnam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout, QLabel, QLineEdit, QPushButton, QMessageBox
from PyQt5.QtGui import QIcon

class Vernam(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(800, 621)
        icon = QIcon("icons/icon.png")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(222, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 801, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)

        font2 = QtGui.QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(75)

        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.lineKey = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineKey.setObjectName("lineKey")
        self.lineKey.setFont(font)
        self.lineKey.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout_2.addWidget(self.lineKey)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.lineShifr = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineShifr.setObjectName("lineShifr")
        self.lineShifr.setFont(font)
        self.lineShifr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.lineShifr)
        self.pushButtonShifr = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonShifr.setFont(font)
        self.pushButtonShifr.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(255, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 0, 0);\n"
"}")

        self.pushButtonShifr.clicked.connect(self.encrypt)

        self.pushButtonShifr.setObjectName("pushButtonShifr")
        self.verticalLayout.addWidget(self.pushButtonShifr)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setToolTipDuration(-1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.textShifr = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textShifr.setObjectName("textShifr")
        self.textShifr.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textShifr.setFont(font)
        self.verticalLayout.addWidget(self.textShifr)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 779, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.copyright = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(180, 590, 431, 31))
        self.copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copyright.setObjectName("copyright")
        self.copyright.setText("© Виноградов К.С., Шифратор, 2023")
        self.copyright.setFont(font2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Введите ключ:"))
        self.label_6.setText(_translate("MainWindow", "Введите шифруемый текст:"))
        self.pushButtonShifr.setText(_translate("MainWindow", "Зашифровать"))
        self.label_9.setText(_translate("MainWindow", "Зашифрованный текст:"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Шифр Вернама</span></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))

    def encrypt(self):
        text = self.lineShifr.text().lower()
        key = self.lineKey.text().lower()

        if not text or not key:
            self.show_error("Ошибка", "Пожалуйста, введите текст и ключ.")
            return

        if not self.is_valid_input(text) or not self.is_valid_input(key):
            self.show_error("Ошибка", "Текст и ключ должны содержать только русские буквы.")
            return

        if len(text) != len(key):
            self.show_error("Ошибка", "Длины текста и ключа должны совпадать.")
            return

        encrypted_text = self.vernam_cipher(text, key)
        self.textShifr.setText(encrypted_text)

    def vernam_cipher(self, text, key):
        result = ""
        for i in range(len(text)):
            text_char = ord(text[i]) - ord('а')
            key_char = ord(key[i]) - ord('а')
            encrypted_char = (text_char + key_char) % 32
            result += chr(encrypted_char + ord('а'))
        return result

    def is_valid_input(self, input_text):
        return all('а' <= char <= 'я' for char in input_text)

    def show_error(self, title, message):
        msg_box = QMessageBox()
        msg_box.setIcon(QMessageBox.Critical)
        msg_box.setWindowTitle(title)
        msg_box.setText(message)
        msg_box.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Vernam_ = QtWidgets.QMainWindow()
    ui = Vernam()
    ui.setupUi(Vernam_)
    Vernam_.show()
    sys.exit(app.exec_())