# -*- coding: utf-8 -*-

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vizh.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Vizhener(object):
    def setupUi(self, Vizhener):
        Vizhener.setObjectName("Vizhener")
        Vizhener.setFixedSize(800, 621)
        icon = QIcon("icons/icon.png")
        Vizhener.setWindowIcon(icon)
        Vizhener.setStyleSheet("background-color: rgb(222, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(Vizhener)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 10, 281, 41))

        font2 = QtGui.QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(False)
        font2.setWeight(75)

        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setObjectName("label_5")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 39, 801, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color:  rgb(0, 208, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"    font-size:  20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"       background-color:  rgb(60, 165, 189);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(255, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")



        self.verticalLayout.addWidget(self.pushButton_2)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setToolTipDuration(-1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout.addWidget(self.textBrowser)
        Vizhener.setCentralWidget(self.centralwidget)

        self.retranslateUi(Vizhener)
        QtCore.QMetaObject.connectSlotsByName(Vizhener)

        self.copyright = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright.setGeometry(QtCore.QRect(180, 590, 431, 31))
        self.copyright.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copyright.setObjectName("copyright")
        self.copyright.setText("© Виноградов К.С., Шифратор, 2023")
        self.copyright.setFont(font2)





    def retranslateUi(self, Vizhener):
        _translate = QtCore.QCoreApplication.translate
        Vizhener.setWindowTitle(_translate("Vizhener", "Vizhener"))
        self.label_5.setText(_translate("Vizhener", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Шифр Виженера</span></p><p align=\"center\"><span style=\" font-size:16pt;\"><br/></span></p></body></html>"))
        self.label_7.setText(_translate("Vizhener", "Введите ключ:"))
        self.label_6.setText(_translate("Vizhener", "Введите шифруемый текст:"))
        self.pushButton_2.setText(_translate("Vizhener", "Зашифровать"))
        self.label_8.setText(_translate("Vizhener", "Зашифрованный текст:"))
        self.pushButton_2.clicked.connect(self.encrypt)




    def encrypt(self):
        plaintext = self.textEdit_2.toPlainText()
        key = self.lineEdit.text()

        encrypted_text = self.vigenere_encrypt(plaintext, key)
        self.textBrowser.setText(encrypted_text)

    def vigenere_encrypt(self, plaintext, key):
        ciphertext = []
        key = key.upper()

        for i in range(len(plaintext)):
            char = plaintext[i]
            if char.isalpha():
                shift = ord(key[i % len(key)]) - ord('А')
                if char.isupper():
                    encrypted_char = chr(((ord(char) - ord('А') + shift) % 32) + ord('А'))
                else:
                    encrypted_char = chr(((ord(char) - ord('а') + shift) % 32) + ord('а'))
            else:
                encrypted_char = char
            ciphertext.append(encrypted_char)

        return ''.join(ciphertext)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Vizhener = QtWidgets.QMainWindow()
    ui = Ui_Vizhener()
    ui.setupUi(Vizhener)
    Vizhener.show()
    sys.exit(app.exec_())